""" build.py turns resources.csv into data.js 
- It reads resources.csv (Question Number, Topic Name, Resources (Name + URL)) and writes data.js, which the site loads.
"""
import csv
import json
import os
import re
from urllib.parse import unquote, urlsplit
CSV_FILE = "resources.csv"
OUT_FILE = "data.js"
SOURCE_SPLIT = re.compile(r"(?:^|,)\s*\d+\)\s*")
URL_PATTERN = re.compile(r"https?://[^\s,]+")

def label_for(url):
    """Make a short human label out of a URL, e.g. 'Solving linear equations'."""
    path = urlsplit(url).path
    parts = [p for p in path.split("/") if p]
    if not parts:
        return urlsplit(url).netloc
    slug = unquote(parts[-1])
    slug = re.sub(r"\.(aspx|html?|php)$", "", slug, flags=re.I)
    slug = re.sub(r"[a-z0-9]{8,}:", "", slug)
    slug = slug.replace("_", " ").replace("-", " ").replace(":", " ")
    slug = re.sub(r"^\s*\d+\.?\s+", "", slug)
    slug = re.sub(r"\s+", " ", slug).strip()
    if len(slug) < 3:
        return urlsplit(url).netloc
    return slug[0].upper() + slug[1:]

def parse_resources(cell):
    """Turn one messy resources cell into [{"name": ..., "links": [...]}, ...]."""
    sources = []
    for chunk in SOURCE_SPLIT.split(cell):
        chunk = chunk.strip()
        if not chunk:
            continue
        urls = []
        for u in URL_PATTERN.findall(chunk):
            u = u.rstrip(".,;)")
            if u not in urls:  
                urls.append(u)
        if not urls:
            continue
        # The source name is whatever text sits before the first URL.
        name = chunk[: chunk.find("http")].strip().rstrip(":").strip()
        if not name:
            name = "Link"
        links = [{"label": label_for(u), "url": u} for u in urls]
        sources.append({"name": name, "links": links})
    return sources
CONTENT_FILE = "content.js"
CONTENT_HEADER = '''// content.js — the writing for each topic. 
// build.py creates this file once so notes are not overwritten. 
// Each topic takes:
//- summary: one or two sentences, shown at the top of the topic page
//- notes: a list of paragraphs 
//- videos: a list of { title: "...", url: "https://..." }
window.CONTENT = {
'''
CONTENT_ENTRY = '''  {topic}: {{
    summary: "",
    notes: [],
    videos: []
  }}'''

def write_content_scaffold(topics):
    """Create content.js the first time."""
    if os.path.exists(CONTENT_FILE):
        existing = open(CONTENT_FILE, encoding="utf-8").read()
        missing = [t for t in topics if json.dumps(t) not in existing]
        if missing:
            print(f"\n{CONTENT_FILE} has no entry for these topics — add them by hand:")
            for t in missing:
                print(f"  {json.dumps(t)}: {{ summary: \"\", notes: [], videos: [] }},")
        return
    entries = ",\n\n".join(CONTENT_ENTRY.format(topic=json.dumps(t)) for t in topics)
    with open(CONTENT_FILE, "w", encoding="utf-8") as f:
        f.write(CONTENT_HEADER + entries + "\n};\n")
    print(f"Created {CONTENT_FILE} with {len(topics)} blank topics — write your notes there.")

def main():
    questions = []
    with open(CSV_FILE, newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            questions.append(
                {
                    "number": int(row["Question Number"]),
                    "topic": row["Topic Name"].strip(),
                    "sources": parse_resources(row["Resources (Name + URL)"]),
                }
            )
    questions.sort(key=lambda q: q["number"])
    payload = json.dumps(questions, indent=2, ensure_ascii=False)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Generated by build.py — edit resources.csv, then re-run the script.\n")
        f.write("window.QUESTIONS = " + payload + ";\n")
    topics = sorted({q["topic"] for q in questions})
    print(f"Wrote {OUT_FILE}: {len(questions)} questions, {len(topics)} topics.")
    for t in topics:
        count = sum(1 for q in questions if q["topic"] == t)
        label = "question" if count == 1 else "questions"
        print(f"  {count:>2} {label:<9}  {t}")
    write_content_scaffold(topics)
if __name__ == "__main__":
    main()
